### PR TITLE
add version prefix matching for theme version constant.

### PR DESCRIPTION
**Pull request by ctalkington**
@robneu one less version to update by hand :)

### CODE REVIEW

**Comment by ozzyrod** [comment]
Thanks! I'll take a look at this tomorrow and pull it in if all is well, unless rob gets to it before me

**Comment by robneu** [comment]
@ctalkington Do you think it might be worth adding this into the main config? I could see using this same constant on non-Genesis child themes as well. 

It probably also wouldn't be a terrible idea to use a PARENT variant in parent themes to avoid an extra filesystem lookup. I've never really investigated how effective the cache is for puling the theme data and even cached it probably is more overhead than necessary for something as simple as a version number.

**Comment by ctalkington** [comment]
you could go that route. could do a simpler regex such as below which should match (PARENT|CHILD|*)_THEME_VERSION',<whitespace>'<version>

```js
prefix: '_THEME_VERSION\'\,\\s+\''
```

**Comment by robneu** [comment]
:+1: That sounds like a plan to me. I'll close this out and you can either open a new PR on the config or I'll go ahead and get it added tomorrow.

**Comment by ctalkington** [comment]
im pretty sure that theme data is parsed once per load so its likely there's not much impact using that as a source but constants are good for versions too imho.

**Pull request closed without merging**
